#!/usr/bin/env python3
"""
FitClockScalersFromBagz.py

Fits scalers for clock model training data from bagz files generated by pgn_to_clock_bagz.
Extracts statistics needed for the enhanced 3D clock embedding and target variable scaling.

This script processes clock bagz files containing JSON records with the following format:
{
  "fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1",
  "recent_moves": ["e2e4", "e7e5", "g1f3"],
  "rating": 1750,
  "player_clock": 178.5,
  "opponent_clock": 175.0,
  "increment": 2.0,
  "thinking_time": 4.5
}

The script fits scalers for 5 numeric fields according to clock_model.md specifications:
- rating → Standardization (mean, std)
- player_clock → Log-transform then standardize
- opponent_clock → Log-transform then standardize  
- increment → Log-transform then standardize
- thinking_time → Log-transform then standardize (target variable)

Usage:
    python FitClockScalersFromBagz.py --bagz /path/to/clock_data.bagz --output scalers.pkl
    python FitClockScalersFromBagz.py --bagz /path/to/clock_data.bagz --output scalers.pkl --num_samples 500000
"""

import argparse
import json
import pickle
import numpy as np
import math
import random
from tqdm.auto import tqdm
from bagz import BagReader


def validate_numeric_field(value, field_name, min_val=0, max_val=None):
    """
    Validate that a field contains a valid numeric value within specified bounds.
    
    Args:
        value: The value to validate
        field_name: Name of the field for error reporting
        min_val: Minimum allowed value (default: 0)
        max_val: Maximum allowed value (default: None for no limit)
        
    Returns:
        bool: True if the value is valid, False otherwise
    """
    try:
        # Check if value is numeric
        if not isinstance(value, (int, float)):
            return False
        
        # Check for NaN or infinite values
        if math.isnan(value) or math.isinf(value):
            return False
        
        # Check minimum bound
        if min_val is not None and value < min_val:
            return False
            
        # Check maximum bound
        if max_val is not None and value > max_val:
            return False
            
        return True
        
    except (TypeError, ValueError):
        return False


def validate_clock_record(record_dict):
    """
    Validate that a clock record contains all required fields with valid values.
    
    Args:
        record_dict: Dictionary containing the parsed JSON record
        
    Returns:
        tuple: (bool, str) - (True if valid, error message if invalid)
    """
    required_fields = ['rating', 'player_clock', 'opponent_clock', 'increment', 'thinking_time']
    
    # Check all required fields exist
    for field in required_fields:
        if field not in record_dict:
            return False, f"Missing required field: {field}"
    
    # Validate specific field constraints
    field_validations = [
        ('rating', record_dict['rating'], 0, 10000),
        ('player_clock', record_dict['player_clock'], 0, 3600),
        ('opponent_clock', record_dict['opponent_clock'], 0, 3600),
        ('increment', record_dict['increment'], 0, 60),
        ('thinking_time', record_dict['thinking_time'], 0, 600)
    ]
    
    for field_name, value, min_val, max_val in field_validations:
        if not validate_numeric_field(value, field_name, min_val, max_val):
            return False, f"{field_name}={value} (outside range {min_val}-{max_val} or invalid type)"
    
    return True, ""


def collect_clock_statistics(bag_reader, num_entries, num_samples=1000000):
    """
    Collect statistics from clock bagz records for scaler fitting.
    
    Args:
        bag_reader: BagReader object for the bagz file
        num_entries: Total number of entries in the bagz file
        num_samples: Number of samples to collect for statistics
        
    Returns:
        dict: Statistics dictionary with mean, std, and count for each field
    """
    print(f"\nSampling {num_samples} records from across the database...")
    
    # Adjust sample size if needed
    num_samples = min(num_samples, num_entries)
    
    # Initialize lists for each field
    ratings = []
    log_player_clocks = []
    log_opponent_clocks = []
    log_increments = []
    log_thinking_times = []
    
    # Tracking variables
    samples_collected = 0
    invalid_records = 0
    invalid_reasons = []
    
    # Generate random indices for sampling
    if num_entries > 0:
        # Generate enough indices to account for potential invalid records
        indices_needed = min(num_entries, int(num_samples * 1.2))  # 20% buffer for invalid records
        indices = sorted(random.sample(range(num_entries), indices_needed))
        
        # Sample records
        for idx in tqdm(indices, desc="Sampling records"):
            if samples_collected >= num_samples:
                break
                
            try:
                # Get the record at the target index
                record = bag_reader[idx]
                
                # Parse the JSON record
                record_data = json.loads(record)
                
                # Validate the record
                is_valid, error_msg = validate_clock_record(record_data)
                if not is_valid:
                    invalid_records += 1
                    invalid_reasons.append(f"Index {idx}: {error_msg}")
                    continue
                
                # Extract and transform numeric fields
                rating = record_data['rating']
                player_clock = record_data['player_clock']
                opponent_clock = record_data['opponent_clock']
                increment = record_data['increment']
                thinking_time = record_data['thinking_time']
                
                # Apply transformations
                ratings.append(rating)  # No transform for rating
                log_player_clocks.append(math.log(player_clock + 1))
                log_opponent_clocks.append(math.log(opponent_clock + 1))
                log_increments.append(math.log(increment + 1))
                log_thinking_times.append(math.log(thinking_time + 1))
                
                samples_collected += 1
                
            except Exception as e:
                invalid_records += 1
                invalid_reasons.append(f"Index {idx}: Exception - {str(e)}")
                continue
    
    print(f"Collected {samples_collected} valid samples ({invalid_records} invalid records skipped)")
    
    # Report invalid records if any
    if invalid_reasons:
        print(f"\nInvalid record details:")
        for i, reason in enumerate(invalid_reasons[:10]):  # Show first 10
            print(f"  {i+1}. {reason}")
        if len(invalid_reasons) > 10:
            print(f"  ... and {len(invalid_reasons) - 10} more")
    
    # Calculate statistics for each field
    stats = {}
    
    if samples_collected > 0:
        # Rating statistics (no transformation)
        if ratings:
            stats['rating'] = {
                'mean': float(np.mean(ratings)),
                'std': float(np.std(ratings)),
                'count': len(ratings),
                'raw_stats': {
                    'min': float(np.min(ratings)),
                    'max': float(np.max(ratings)),
                    'median': float(np.median(ratings))
                }
            }
        
        # Log player clock statistics
        if log_player_clocks:
            raw_player_clocks = [math.exp(log_val) - 1 for log_val in log_player_clocks]
            stats['log_player_clock'] = {
                'mean': float(np.mean(log_player_clocks)),
                'std': float(np.std(log_player_clocks)),
                'count': len(log_player_clocks),
                'raw_stats': {
                    'min': float(np.min(raw_player_clocks)),
                    'max': float(np.max(raw_player_clocks)),
                    'median': float(np.median(raw_player_clocks))
                }
            }
        
        # Log opponent clock statistics
        if log_opponent_clocks:
            raw_opponent_clocks = [math.exp(log_val) - 1 for log_val in log_opponent_clocks]
            stats['log_opponent_clock'] = {
                'mean': float(np.mean(log_opponent_clocks)),
                'std': float(np.std(log_opponent_clocks)),
                'count': len(log_opponent_clocks),
                'raw_stats': {
                    'min': float(np.min(raw_opponent_clocks)),
                    'max': float(np.max(raw_opponent_clocks)),
                    'median': float(np.median(raw_opponent_clocks))
                }
            }
        
        # Log increment statistics
        if log_increments:
            raw_increments = [math.exp(log_val) - 1 for log_val in log_increments]
            stats['log_increment'] = {
                'mean': float(np.mean(log_increments)),
                'std': float(np.std(log_increments)),
                'count': len(log_increments),
                'raw_stats': {
                    'min': float(np.min(raw_increments)),
                    'max': float(np.max(raw_increments)),
                    'median': float(np.median(raw_increments))
                }
            }
        
        # Log thinking time statistics (target variable)
        if log_thinking_times:
            raw_thinking_times = [math.exp(log_val) - 1 for log_val in log_thinking_times]
            stats['log_thinking_time'] = {
                'mean': float(np.mean(log_thinking_times)),
                'std': float(np.std(log_thinking_times)),
                'count': len(log_thinking_times),
                'raw_stats': {
                    'min': float(np.min(raw_thinking_times)),
                    'max': float(np.max(raw_thinking_times)),
                    'median': float(np.median(raw_thinking_times))
                }
            }
        
        # Print summary statistics
        print(f"\nFitted scaler statistics:")
        for field_name, field_stats in stats.items():
            print(f"\n{field_name}:")
            print(f"  Transformed - Mean: {field_stats['mean']:.4f}, Std: {field_stats['std']:.4f}")
            print(f"  Raw values - Min: {field_stats['raw_stats']['min']:.2f}, "
                  f"Max: {field_stats['raw_stats']['max']:.2f}, "
                  f"Median: {field_stats['raw_stats']['median']:.2f}")
            print(f"  Sample count: {field_stats['count']}")
    else:
        print("No valid samples found in the bagz file.")
    
    return stats


def calculate_clock_scalers(bagz_path, output_path, num_samples=1000000):
    """
    Load data from a clock bagz file and calculate scalers for clock model training.
    
    Args:
        bagz_path: Path to the clock bagz file
        output_path: Path to save the pickle file containing scalers
        num_samples: Number of samples to collect for statistics (default: 1,000,000)
    """
    print(f"Opening clock bagz file: {bagz_path}")
    
    try:
        bag_reader = BagReader(bagz_path)
        num_entries = len(bag_reader)
        print(f"Clock bagz file contains {num_entries} entries")
        
        if num_entries == 0:
            print("Error: Bagz file is empty")
            return
        
        # Collect statistics
        stats = collect_clock_statistics(bag_reader, num_entries, num_samples)
        
        if not stats:
            print("Error: No valid statistics collected from the bagz file")
            return
        
        # Validate statistics before saving
        for field_name, field_stats in stats.items():
            if field_stats['std'] <= 0:
                print(f"Warning: {field_name} has zero or negative standard deviation: {field_stats['std']}")
            if math.isnan(field_stats['mean']) or math.isnan(field_stats['std']):
                print(f"Error: {field_name} has NaN values in statistics")
                return
        
        # Save the statistics to a pickle file
        try:
            with open(output_path, 'wb') as f:
                pickle.dump(stats, f)
            print(f"\nClock scalers saved to {output_path}")
            
            # Validate saved file
            with open(output_path, 'rb') as f:
                loaded_stats = pickle.load(f)
            print(f"Successfully validated saved scalers file with {len(loaded_stats)} field types")
            
        except Exception as e:
            print(f"Error saving scalers to {output_path}: {e}")
            raise
        
    except Exception as e:
        print(f"Error processing bagz file {bagz_path}: {e}")
        raise


def main():
    """Main CLI interface for fitting clock scalers from bagz files."""
    parser = argparse.ArgumentParser(
        description="Fit scalers for clock model training from clock bagz files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --bagz /path/to/clock_data.bagz --output clock_scalers.pkl
  %(prog)s --bagz /path/to/clock_data.bagz --output clock_scalers.pkl --num_samples 500000
        """
    )
    
    parser.add_argument("--bagz", type=str, required=True,
                        help="Path to the clock bagz file generated by pgn_to_clock_bagz")
    parser.add_argument("--output", type=str, required=True,
                        help="Path to save the pickle file containing fitted scalers")
    parser.add_argument("--num_samples", type=int, default=1000000,
                        help="Number of samples to collect for statistics (default: 1,000,000)")
    
    args = parser.parse_args()
    
    # Validate input arguments
    if args.num_samples <= 0:
        print("Error: num_samples must be positive")
        return
    
    # Run the main calculation
    calculate_clock_scalers(args.bagz, args.output, args.num_samples)


if __name__ == "__main__":
    main()
