#!/usr/bin/env python3
"""
FitWinnerScalersFromBagz.py

Fits scalers for winner prediction model training data from bagz files generated by pgn_to_winner_bagz.
Extracts statistics needed for feature scaling.

This script processes winner bagz files containing JSON records with the following format:
{
  "fen": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1",
  "recent_moves": ["e2e4"],
  "winner": 1,  # -1 for black, 0 for draw, 1 for white
  "white_rating": 1800,
  "black_rating": 1750,
  "white_clock": 180.0,
  "black_clock": 178.5,
  "increment": 2.0
}

The script fits scalers for 5 numeric fields:
- white_rating → Standardization (mean, std)
- black_rating → Standardization (mean, std)
- white_clock → Log-transform then standardize
- black_clock → Log-transform then standardize
- increment → Log-transform then standardize

Usage:
    python FitWinnerScalersFromBagz.py --bagz /path/to/winner_data.bagz --output scalers.pkl
    python FitWinnerScalersFromBagz.py --bagz /path/to/winner_data.bagz --output scalers.pkl --num_samples 500000
"""

import argparse
import json
import pickle
import numpy as np
import math
import random
from tqdm.auto import tqdm
from bagz import BagReader


def validate_numeric_field(value, field_name, min_val=0, max_val=None):
    """
    Validate that a field contains a valid numeric value within specified bounds.
    
    Args:
        value: The value to validate
        field_name: Name of the field for error reporting
        min_val: Minimum allowed value (default: 0)
        max_val: Maximum allowed value (default: None for no limit)
        
    Returns:
        bool: True if the value is valid, False otherwise
    """
    try:
        # Check if value is numeric
        if not isinstance(value, (int, float)):
            return False
        
        # Check for NaN or infinite values
        if math.isnan(value) or math.isinf(value):
            return False
        
        # Check minimum bound
        if min_val is not None and value < min_val:
            return False
            
        # Check maximum bound
        if max_val is not None and value > max_val:
            return False
            
        return True
        
    except (TypeError, ValueError):
        return False


def validate_winner_record(record_dict):
    """
    Validate that a winner record contains all required fields with valid values.
    
    Args:
        record_dict: Dictionary containing the parsed JSON record
        
    Returns:
        tuple: (bool, str) - (True if valid, error message if invalid)
    """
    required_fields = ['winner', 'white_rating', 'black_rating', 'white_clock', 'black_clock', 'increment']
    
    # Check all required fields exist
    for field in required_fields:
        if field not in record_dict:
            return False, f"Missing required field: {field}"
    
    # Validate winner field specifically
    winner = record_dict['winner']
    if winner not in [-1, 0, 1]:
        return False, f"Invalid winner value: {winner} (must be -1, 0, or 1)"
    
    # Validate specific field constraints
    field_validations = [
        ('white_rating', record_dict['white_rating'], 100, 4000),
        ('black_rating', record_dict['black_rating'], 100, 4000),
        ('white_clock', record_dict['white_clock'], 0, 7200),  # up to 2 hours
        ('black_clock', record_dict['black_clock'], 0, 7200),
        ('increment', record_dict['increment'], 0, 120)  # up to 2 minutes
    ]
    
    for field_name, value, min_val, max_val in field_validations:
        if not validate_numeric_field(value, field_name, min_val, max_val):
            return False, f"{field_name}={value} (outside range {min_val}-{max_val} or invalid type)"
    
    return True, ""


def collect_winner_statistics(bag_reader, num_entries, num_samples=1000000):
    """
    Collect statistics from winner bagz records for scaler fitting.
    
    Args:
        bag_reader: BagReader object for the bagz file
        num_entries: Total number of entries in the bagz file
        num_samples: Number of samples to collect for statistics
        
    Returns:
        dict: Statistics dictionary with mean, std, and count for each field
    """
    print(f"\nSampling {num_samples} records from across the database...")
    
    # Adjust sample size if needed
    num_samples = min(num_samples, num_entries)
    
    # Initialize lists for each field
    white_ratings = []
    black_ratings = []
    log_white_clocks = []
    log_black_clocks = []
    log_increments = []
    
    # Winner distribution tracking
    winner_counts = {'black': 0, 'draw': 0, 'white': 0}
    
    # Tracking variables
    samples_collected = 0
    invalid_records = 0
    invalid_reasons = []
    
    # Generate random indices for sampling
    if num_entries > 0:
        # Generate enough indices to account for potential invalid records
        indices_needed = min(num_entries, int(num_samples * 1.2))  # 20% buffer for invalid records
        indices = sorted(random.sample(range(num_entries), indices_needed))
        
        # Sample records
        for idx in tqdm(indices, desc="Sampling records"):
            if samples_collected >= num_samples:
                break
                
            try:
                # Get the record at the target index
                record = bag_reader[idx]
                
                # Parse the JSON record
                record_data = json.loads(record)
                
                # Validate the record
                is_valid, error_msg = validate_winner_record(record_data)
                if not is_valid:
                    invalid_records += 1
                    invalid_reasons.append(f"Index {idx}: {error_msg}")
                    continue
                
                # Extract fields
                winner = record_data['winner']
                white_rating = record_data['white_rating']
                black_rating = record_data['black_rating']
                white_clock = record_data['white_clock']
                black_clock = record_data['black_clock']
                increment = record_data['increment']
                
                # Track winner distribution
                if winner == -1:
                    winner_counts['black'] += 1
                elif winner == 0:
                    winner_counts['draw'] += 1
                else:  # winner == 1
                    winner_counts['white'] += 1
                
                # Apply transformations
                white_ratings.append(white_rating)  # No transform for ratings
                black_ratings.append(black_rating)
                log_white_clocks.append(math.log(white_clock + 1))
                log_black_clocks.append(math.log(black_clock + 1))
                log_increments.append(math.log(increment + 1))
                
                samples_collected += 1
                
            except Exception as e:
                invalid_records += 1
                invalid_reasons.append(f"Index {idx}: Exception - {str(e)}")
                continue
    
    print(f"Collected {samples_collected} valid samples ({invalid_records} invalid records skipped)")
    
    # Report invalid records if any
    if invalid_reasons:
        print(f"\nInvalid record details:")
        for i, reason in enumerate(invalid_reasons[:10]):  # Show first 10
            print(f"  {i+1}. {reason}")
        if len(invalid_reasons) > 10:
            print(f"  ... and {len(invalid_reasons) - 10} more")
    
    # Print winner distribution
    if samples_collected > 0:
        print(f"\nWinner distribution:")
        for outcome, count in winner_counts.items():
            pct = 100.0 * count / samples_collected
            print(f"  {outcome.capitalize()}: {count} ({pct:.2f}%)")
    
    # Calculate statistics for each field
    stats = {}
    
    if samples_collected > 0:
        # White rating statistics (no transformation)
        if white_ratings:
            stats['white_rating'] = {
                'mean': float(np.mean(white_ratings)),
                'std': float(np.std(white_ratings)),
                'count': len(white_ratings),
                'raw_stats': {
                    'min': float(np.min(white_ratings)),
                    'max': float(np.max(white_ratings)),
                    'median': float(np.median(white_ratings))
                }
            }
        
        # Black rating statistics (no transformation)
        if black_ratings:
            stats['black_rating'] = {
                'mean': float(np.mean(black_ratings)),
                'std': float(np.std(black_ratings)),
                'count': len(black_ratings),
                'raw_stats': {
                    'min': float(np.min(black_ratings)),
                    'max': float(np.max(black_ratings)),
                    'median': float(np.median(black_ratings))
                }
            }
        
        # Log white clock statistics
        if log_white_clocks:
            raw_white_clocks = [math.exp(log_val) - 1 for log_val in log_white_clocks]
            stats['log_white_clock'] = {
                'mean': float(np.mean(log_white_clocks)),
                'std': float(np.std(log_white_clocks)),
                'count': len(log_white_clocks),
                'raw_stats': {
                    'min': float(np.min(raw_white_clocks)),
                    'max': float(np.max(raw_white_clocks)),
                    'median': float(np.median(raw_white_clocks))
                }
            }
        
        # Log black clock statistics
        if log_black_clocks:
            raw_black_clocks = [math.exp(log_val) - 1 for log_val in log_black_clocks]
            stats['log_black_clock'] = {
                'mean': float(np.mean(log_black_clocks)),
                'std': float(np.std(log_black_clocks)),
                'count': len(log_black_clocks),
                'raw_stats': {
                    'min': float(np.min(raw_black_clocks)),
                    'max': float(np.max(raw_black_clocks)),
                    'median': float(np.median(raw_black_clocks))
                }
            }
        
        # Log increment statistics
        if log_increments:
            raw_increments = [math.exp(log_val) - 1 for log_val in log_increments]
            stats['log_increment'] = {
                'mean': float(np.mean(log_increments)),
                'std': float(np.std(log_increments)),
                'count': len(log_increments),
                'raw_stats': {
                    'min': float(np.min(raw_increments)),
                    'max': float(np.max(raw_increments)),
                    'median': float(np.median(raw_increments))
                }
            }
        
        # Print summary statistics
        print(f"\nFitted scaler statistics:")
        for field_name, field_stats in stats.items():
            print(f"\n{field_name}:")
            print(f"  Transformed - Mean: {field_stats['mean']:.4f}, Std: {field_stats['std']:.4f}")
            print(f"  Raw values - Min: {field_stats['raw_stats']['min']:.2f}, "
                  f"Max: {field_stats['raw_stats']['max']:.2f}, "
                  f"Median: {field_stats['raw_stats']['median']:.2f}")
            print(f"  Sample count: {field_stats['count']}")
    else:
        print("No valid samples found in the bagz file.")
    
    return stats


def calculate_winner_scalers(bagz_path, output_path, num_samples=1000000):
    """
    Load data from a winner bagz file and calculate scalers for winner model training.
    
    Args:
        bagz_path: Path to the winner bagz file
        output_path: Path to save the pickle file containing scalers
        num_samples: Number of samples to collect for statistics (default: 1,000,000)
    """
    print(f"Opening winner bagz file: {bagz_path}")
    
    try:
        bag_reader = BagReader(bagz_path)
        num_entries = len(bag_reader)
        print(f"Winner bagz file contains {num_entries} entries")
        
        if num_entries == 0:
            print("Error: Bagz file is empty")
            return
        
        # Collect statistics
        stats = collect_winner_statistics(bag_reader, num_entries, num_samples)
        
        if not stats:
            print("Error: No valid statistics collected from the bagz file")
            return
        
        # Validate statistics before saving
        for field_name, field_stats in stats.items():
            if field_stats['std'] <= 0:
                print(f"Warning: {field_name} has zero or negative standard deviation: {field_stats['std']}")
            if math.isnan(field_stats['mean']) or math.isnan(field_stats['std']):
                print(f"Error: {field_name} has NaN values in statistics")
                return
        
        # Save the statistics to a pickle file
        try:
            with open(output_path, 'wb') as f:
                pickle.dump(stats, f)
            print(f"\nWinner scalers saved to {output_path}")
            
            # Validate saved file
            with open(output_path, 'rb') as f:
                loaded_stats = pickle.load(f)
            print(f"Successfully validated saved scalers file with {len(loaded_stats)} field types")
            
        except Exception as e:
            print(f"Error saving scalers to {output_path}: {e}")
            raise
        
    except Exception as e:
        print(f"Error processing bagz file {bagz_path}: {e}")
        raise


def main():
    """Main CLI interface for fitting winner scalers from bagz files."""
    parser = argparse.ArgumentParser(
        description="Fit scalers for winner prediction model training from winner bagz files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --bagz /path/to/winner_data.bagz --output winner_scalers.pkl
  %(prog)s --bagz /path/to/winner_data.bagz --output winner_scalers.pkl --num_samples 500000
        """
    )
    
    parser.add_argument("--bagz", type=str, required=True,
                        help="Path to the winner bagz file generated by pgn_to_winner_bagz")
    parser.add_argument("--output", type=str, required=True,
                        help="Path to save the pickle file containing fitted scalers")
    parser.add_argument("--num_samples", type=int, default=1000000,
                        help="Number of samples to collect for statistics (default: 1,000,000)")
    
    args = parser.parse_args()
    
    # Validate input arguments
    if args.num_samples <= 0:
        print("Error: num_samples must be positive")
        return
    
    # Run the main calculation
    calculate_winner_scalers(args.bagz, args.output, args.num_samples)


if __name__ == "__main__":
    main()