/**
 * Common chess.js mock configuration for tests
 */

export const createMockChessGame = (overrides = {}) => ({
  fen: jest.fn(() => 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'),
  turn: jest.fn(() => 'w'),
  isGameOver: jest.fn(() => false),
  history: jest.fn(() => []),
  pgn: jest.fn(() => ''),
  isCheck: jest.fn(() => false),
  isCheckmate: jest.fn(() => false),
  isStalemate: jest.fn(() => false),
  isInsufficientMaterial: jest.fn(() => false),
  isThreefoldRepetition: jest.fn(() => false),
  isDraw: jest.fn(() => false),
  move: jest.fn(),
  undo: jest.fn(),
  reset: jest.fn(),
  load: jest.fn(() => true),
  loadPgn: jest.fn(() => true),
  get: jest.fn(() => null),
  remove: jest.fn(() => null),
  put: jest.fn(() => true),
  moves: jest.fn(() => ['e4', 'e5', 'd4', 'd5', 'Nf3', 'Nc6']),
  inCheck: jest.fn(() => false),
  inCheckmate: jest.fn(() => false),
  inStalemate: jest.fn(() => false),
  inDraw: jest.fn(() => false),
  header: jest.fn(),
  ascii: jest.fn(() => ''),
  clear: jest.fn(),
  ...overrides
});

export const createMockUseChessGame = (overrides = {}) => ({
  game: createMockChessGame(),
  moveHistory: [],
  viewedPlyIndex: -1,
  moveToPromote: null,
  legalSquares: [],
  squareStyles: {},
  selectedPiece: null,
  lastMoveSquares: { from: null, to: null },
  isViewingLatest: true,
  enhancedHistory: [],
  setGame: jest.fn(),
  setMoveHistory: jest.fn(),
  setViewedPlyIndex: jest.fn(),
  setMoveToPromote: jest.fn(),
  setLegalSquares: jest.fn(),
  setSquareStyles: jest.fn(),
  setSelectedPiece: jest.fn(),
  setLastMoveSquares: jest.fn(),
  resetGame: jest.fn(() => createMockChessGame()),
  loadFEN: jest.fn(),
  loadPGN: jest.fn(),
  makeMove: jest.fn(),
  handlePromotion: jest.fn(),
  goToPly: jest.fn(),
  selectPiece: jest.fn(),
  isLegalMove: jest.fn(),
  updateLastMoveSquares: jest.fn(),
  getViewedFEN: jest.fn(() => 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'),
  loadGameFromFEN: jest.fn(),
  navigateToPly: jest.fn(),
  ...overrides
});

export const createMockUseChessClock = (overrides = {}) => ({
  whiteTime: 300000,
  blackTime: 300000,
  activeColor: null,
  clockRunning: false,
  gameEndedByTime: false,
  timeWinner: null,
  moveTimes: [],
  handleMoveCompletion: jest.fn(),
  stopClock: jest.fn(),
  resetClock: jest.fn(),
  addMoveTime: jest.fn(),
  setClockRunning: jest.fn(),
  ...overrides
});